version: '3.7'
 
services:
  app:
    build: 
      context: .
      dockerfile: ops/docker/app/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/app:rw

  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
    volumes:
      - db_data

volumes:
  db_data:
